version: '3'

services:
  app:  #&app
    container_name: app-web_speller
    build:
      context: .
      dockerfile: ./docker/local/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./shared/media:/app/shared/media
      - ./shared/static:/app/shared/static
      - ./shared/templates:/app/shared/templates

  redis:
    container_name: redis-web_speller
    image: redis:3.0
    ports:
      - "6379:6379"
    env_file:
      - .env
